fix: ignore a test for memory issues on the CI
One test has been added by @nharrand in #2112 to show the usage of the new dependency resolver. However this test consumes too much memory on our CI, on the job used to deploy maven artefacts: 
> [ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 68.03 s <<< FAILURE! - in spoon.MavenLauncherTest
[ERROR] testTypeResolution(spoon.MavenLauncherTest)  Time elapsed: 38.801 s  <<< ERROR!
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at spoon.MavenLauncherTest.testTypeResolution(MavenLauncherTest.java:25)

https://ci.inria.fr/sos/job/Spoon-Snapshot-Deployer/1689/console

I propose to ignore the test for now.