Bug: SniperPrettyPrinter fails when calling toString
Failing test case which showcases how SniperPrettyPrinter crashes with
SpoonException: Missing SourceFragmentContext when calling toString on
a CtElement.

To see that it is the SniperPrettyPrinter which fails, lines 181-184
can be commented to deactivate SniperPretty. The tet then passes.